on:
  push:
  workflow_dispatch:
permissions: write-all 
jobs:
  build:
    uses: gardenlinux/package-build/.github/workflows/build.yml@sha-sum-release-files
    with:
      release: true
      runs-on-arm64: ubuntu-24.04-arm
